---
# Fallback naming prefix
vm_name_prefix: "{{ ocp_cluster.name | default('ocp4') }}"

# Default Hardware Specs
vm_specs:
  bootstrap:
    cpu: 4
    memory_mb: 16384
    disk_gb: 120
  master:
    cpu: 8
    memory_mb: 32768
    disk_gb: 120
  worker:
    cpu: 8
    memory_mb: 32768
    disk_gb: 120