---
- name: "Create {{ node_type | capitalize }} VMs in VMware"
  community.vmware.vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    validate_certs: false
    datacenter: "{{ vcenter.datacenter }}"
    cluster: "{{ vcenter.cluster }}"
    folder: "{{ vcenter.folder }}"

    # Custom Naming Logic: Uses explicitly defined name, falls back to default prefix + type + index
    name: "{{ item.name | default(vm_name_prefix + '-' + node_type + '-' + node_idx|string) }}"

    template: "{{ vcenter.rhcos_template }}"
    state: poweredon
    hardware:
      memory_mb: "{{ vm_specs[node_type].memory_mb }}"
      num_cpus: "{{ vm_specs[node_type].cpu }}"
    disk:
      - size_gb: "{{ vm_specs[node_type].disk_gb }}"
        type: thin
        datastore: "{{ vcenter.datastore }}"
    networks:
      - name: "{{ vcenter.network }}"
        # Mac address mapping can be added here if you are using static DHCP reservations
        mac: "{{ item.mac | default(omit) }}"
    advanced_settings:
      # Inject the Base64 encoded ignition config directly into the VM properties
      - key: guestinfo.ignition.config.data
        value: "{{ (ignition_data.results | selectattr('item', 'equalto', node_type) | first).content }}"
      - key: guestinfo.ignition.config.data.encoding
        value: base64
      - key: disk.EnableUUID
        value: "TRUE"
  loop: "{{ node_list }}"
  loop_control:
    index_var: node_idx